### PR TITLE
About screen formatting fixes

### PR DESCRIPTION
**Pull request by julianxcarter**
Updates the styling on the About screen to properly format on mobile devices.

### CODE REVIEW

**Comment by julianxcarter** [comment]
Screen Shot 2022-05-23 at 12 18 49 PM

https://user-images.githubusercontent.com/53443041/169863742-bcf7add7-3219-4c6c-9096-f972c06a47a0.mov

**Review by cmoesel — APPROVED** [review]
Yeah, OK.  Looks better to me!  Let's merge and try it on a real phone!

**Comment by cmoesel** [comment]
CONFIRMED!  Much better!

**Review by markkramerus — COMMENTED** [review]
Looks good.

**Pull request merged**
