### PR TITLE
Update Presentations

### PR DESCRIPTION
**Pull request by jafeltra**
This PR updates the links to past presentations. Since some of the newer presentations covered the same topics and some of the older presentations felt outdated, I reorganized the section. The general order I was aiming for was intro materials at the top, increasing in complexity as you go down the list. 

The presentations I removed were from the September 2020 Connectathon. I think the majority of the information was covered in the other presentations currently linked. There was a lot of info that has been updated since then, like GoFSH is no longer a beta. The main things that the Intro and Advanced presentations had that doesn't feel as explicitly covered are walk-throughs of the different types of rules and FSH items (you can take a look at them easily on the current site [here](https://fshschool.org/downloads/#tutorials-from-the-hl7-fhir-connectathon-september-2020)). However, I felt that the other information in those slides was outdated enough and there are enough other resources to learn about individual rules on Language Reference/FSH Online that it was better to remove them. If anyone thinks they are worthwhile to keep though, just let me know!

I also updated the favicons to be the newer fish logo that Noranda had designed that's used throughout the presentations and the site.

### CODE REVIEW

**Comment by cmoesel** [comment]
Thanks, @jafeltra! I have a few questions...

1. Do you think that the presentations from Nov 2020 and June 2021 are all needed? Is there significant stuff that Nov 2020 covers that June 2021 does not?

2. Why is the last "Let's Build - Create an Implementation Guide" a sub-bullet instead of a top-level bullet?  And why isn't there a link to the slides?

**Comment by jafeltra** [comment]
A few answers!

1. I left the November 2020 presentations because they seemed to cover more basics in more detail than the June 2021 presentations. I think the June 2021 presentations touch on all the same materials, but the November ones seemed to walk through them more slowly.

2a. It seemed to be a natural continuation of the presentation on creating an IG, but I went back and forth on the placement, so I can definitely be convinced to make it it's own bullet.

2b. I couldn't find any corresponding slides posted on the [June 2021 DevDays site](https://www.devdays.com/devdays-virtual-edition-june-2021/presentations/) for the Let's Build session. Mark seems to be walking through slides along side the code he is writing, so they must exist somewhere. I can reach out to him for them, unless you know of a place internally they might be posted.

**Comment by cmoesel** [comment]
Thanks, @jafeltra.

1. OK.  That makes sense!
2. I think it would make more sense to just list it separately (like the others).  I have an internal link to the PPTX.  I'll send it to you over slack.

**Comment by jafeltra** [comment]
Thanks @cmoesel! [6754003](https://github.com/FSHSchool/site/pull/55/commits/67540031379f86b67855a61d4b98ca929025fb8a) should take care of both points in 2!

**Review by cmoesel — APPROVED** [review]
Looks good, @jafeltra!  Thanks!

**Pull request merged**
